# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Add tag and create a new release"
  lane :create_new_release do
    last_commit = last_git_commit
    changelog = last_commit[:message]
    
    # There isn't a "version" on packages, so we can just
    # grab the last tag, increment the minor version and
    # push that tag
    last_tag = last_git_tag
    
    # bump the minor number and reset the patch number
    # if the major version needs to change, that needs to happen manually
    parts = last_tag.split(".")
    parts[1] = parts[1].to_i + 1
    parts[2] = "0"
    new_tag = parts.join(".")
    
    add_git_tag(tag: new_tag)
    push_git_tags
    
    set_github_release(
		repository_name: "TodayTix/iosDesignTokens",
		api_token: ENV["GITHUB_API_TOKEN"],
		name: new_tag,
		tag_name: new_tag,
		description: changelog,
	)
  end
end
